# Generated by Django 4.0.6 on 2022-09-11 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapi', '0005_userprofile_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followings',
            field=models.ManyToManyField(null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
